name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t message-image .

    - name: Save Docker Image Result
      run: |
        docker save message-image -o result.tar
        mkdir -p github_workspace/artifacts
        mv result.tar github_workspace/artifacts
      if: success()

    - name: Upload Result
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: github_workspace/artifacts
    
